# Generated by Django 5.2.1 on 2025-09-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_shippingaddress_order_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color_code',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
