# Generated by Django 5.2.1 on 2025-09-09 22:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
