# Generated by Django 5.2.1 on 2025-10-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.CharField(default='13', max_length=20),
        ),
    ]
